### ISSUE TITLE
AssertionError: <pre> tag should be coupled: "undefined" <=> "</pre>"

### ISSUE THREAD

**Issue by airclear** [vuejs/cn.vuejs.org#354]
环境
```
hexo: 3.3.6
hexo-cli: 1.0.2
os: Darwin 15.6.0 darwin x64
http_parser: 2.7.0
node: 6.10.0
v8: 5.1.281.93
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 58.2
modules: 48
openssl: 1.0.2k
```

错误：
可能跟这个相关：https://github.com/vuejs/vuejs.org/issues/895
```
$ hexo server -p 4001
[BS] Access URLs:
 ---------------------------------------
          UI: http://localhost:3001
 ---------------------------------------
 UI External: http://192.168.12.206:3001
 ---------------------------------------
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
AssertionError: <pre> tag should be coupled: "undefined" <=> "</pre>"
    at escapeContent (/Users/airclear/works/projects/cn.vuejs.org/node_modules/hexo/lib/extend/tag.js:62:5)
    at RegExp.[Symbol.replace] (native)
    at RegExp.[Symbol.replace] (native)
    at String.replace (native)
    at /Users/airclear/works/projects/cn.vuejs.org/node_modules/hexo/lib/extend/tag.js:71:15
    at Promise._execute (/Users/airclear/works/projects/cn.vuejs.org/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/Users/airclear/works/projects/cn.vuejs.org/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/Users/airclear/works/projects/cn.vuejs.org/node_modules/bluebird/js/release/promise.js:79:10)
    at Tag.render (/Users/airclear/works/projects/cn.vuejs.org/node_modules/hexo/lib/extend/tag.js:70:10)
    at Object.tagFilter [as onRenderEnd] (/Users/airclear/works/projects/cn.vuejs.org/node_modules/hexo/lib/hexo/post.js:253:16)
    at /Users/airclear/works/projects/cn.vuejs.org/node_modules/hexo/lib/hexo/render.js:65:19
    at tryCatcher (/Users/airclear/works/projects/cn.vuejs.org/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/airclear/works/projects/cn.vuejs.org/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/airclear/works/projects/cn.vuejs.org/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/airclear/works/projects/cn.vuejs.org/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/airclear/works/projects/cn.vuejs.org/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/airclear/works/projects/cn.vuejs.org/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/airclear/works/projects/cn.vuejs.org/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/airclear/works/projects/cn.vuejs.org/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
FATAL <pre> tag should be coupled: "undefined" <=> "</pre>"
AssertionError: <pre> tag should be coupled: "undefined" <=> "</pre>"
    at escapeContent (/Users/airclear/works/projects/cn.vuejs.org/node_modules/hexo/lib/extend/tag.js:62:5)
    at RegExp.[Symbol.replace] (native)
    at RegExp.[Symbol.replace] (native)
    at String.replace (native)
    at /Users/airclear/works/projects/cn.vuejs.org/node_modules/hexo/lib/extend/tag.js:71:15
    at Promise._execute (/Users/airclear/works/projects/cn.vuejs.org/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/Users/airclear/works/projects/cn.vuejs.org/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/Users/airclear/works/projects/cn.vuejs.org/node_modules/bluebird/js/release/promise.js:79:10)
    at Tag.render (/Users/airclear/works/projects/cn.vuejs.org/node_modules/hexo/lib/extend/tag.js:70:10)
    at Object.tagFilter [as onRenderEnd] (/Users/airclear/works/projects/cn.vuejs.org/node_modules/hexo/lib/hexo/post.js:253:16)
    at /Users/airclear/works/projects/cn.vuejs.org/node_modules/hexo/lib/hexo/render.js:65:19
    at tryCatcher (/Users/airclear/works/projects/cn.vuejs.org/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/airclear/works/projects/cn.vuejs.org/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/airclear/works/projects/cn.vuejs.org/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/airclear/works/projects/cn.vuejs.org/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/airclear/works/projects/cn.vuejs.org/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/airclear/works/projects/cn.vuejs.org/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/airclear/works/projects/cn.vuejs.org/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/airclear/works/projects/cn.vuejs.org/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
```

**Comment by Jinjiang** [comment]
同 #358 实测 `hexo@3.3.7` 可以正常使用，所以未做进一步处理。感谢
